version: '3.3'

services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATADASE=persons
    volumes:
    - /home/ruslan/workspace/:/files
  web:
    container_name: product
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      - MONGO_INITDB_DATADASE=product-database
      - INIT_PATH =/files
      - START_DELAY=20000
    depends_on:
      - mongodb
